#!/usr/bin/bash
# Maintainer : Eduardo Charquero <eduardo.charquero@gmail.com>

pkgname=epoptes
pkgver=$(date +%Y%m%d)
pkgrel=$(date +%H%M)
pkgdesc='An opensource computer lab management and monitoring tool'
makedepends=(git python3-distutils-extra intltool)
url="https://github.com/voidlinuxbr/$pkgname"
#source=("git+${url}.git")
license=(GPL3)
arch=(any)
sha256sums=('SKIP')
depends=(gobject-introspection
	gtk+3
	iperf
	iproute2
	faketime
	libnotify
	librsvg
	notification-daemon
	openssl
	python3-cairo
	python3-dbus
	python3-gobject
	python3-netifaces
	python3-openssl
	python3-service_identity
	python3-Twisted
	socat
	tigervnc
	x11vnc
	xterm)
optdepends=('xfce4-notifyd: XFCE notification support')

package() {
	local dirs=("usr" "etc" "opt")
	#   echo "DESTDIR=$DESTDIR"
	#   echo "pkgdir=$pkgdir"
	#   echo "srcdir=$srcdir"
	#   echo "_pkgsrc=$_pkgsrc"

	cd ${srcdir}/${pkgname}
	for dir in "${dirs[@]}"; do
		if [ -d "${_pkgsrc}/${dir}" ]; then
			cp -a "${_pkgsrc}/${dir}" "$DESTDIR/"
		fi
	done
}

pre_install() {
	log "Iniciando instalação"
}

post_install() {

	if getent group epoptes; then
		echo "Group 'epoptes' already exists. Skipping group's creation."
	else
		groupadd epoptes || true
		echo "Group 'epoptes' has been added."
	fi

	mkdir -p /etc/epoptes/ || true
	if ! [ -s /etc/epoptes/server.key ] || ! [ -s /etc/epoptes/server.crt ]; then
		faketime '1970-01-01 00:00:00 UTC' \
			openssl req -batch -x509 -nodes \
			-newkey rsa:4096 -days $(($(date --utc +%s) / 86400 + 3652)) \
			-keyout /etc/epoptes/server.key -out /etc/epoptes/server.crt
		chmod 600 /etc/epoptes/server.key
	fi

  sed -i 's/import pipes/import shlex/' /usr/lib/python3.14/site-packages/epoptes/ui/gui.py
  sed -i 's/pipes\.quote/shlex.quote/g' /usr/lib/python3.14/site-packages/epoptes/ui/gui.py

  ln -sf /etc/sv/epoptes /var/service/
  echo 'usermod -aG epoptes "$user"'

  log "A instalação foi concluída. Antes de utilizar o Epoptes, lembre-se de fazer o seguinte:"
  log "1.- Você deverá adicionar seu usuário ao grupo 'epoptes' - usermod -aG epoptes "$USER""
  log "2.- Você deverá executar como root:"
  log "    'vservice enable epoptes' para habilitar o serviço do servidor Epoptes."
  log "3.- Pode ser necessário reiniciar o sistema para que tudo funcione corretamente."
  log "4.- Se não quiser reiniciar o sistema, após realizar todos os passos acima, execute como root:"
  log "    'vservice start epoptes' para iniciar o serviço do servidor Epoptes."
  log "Após concluir tudo isso, você ainda precisará encerrar a sessão e entrar novamente."
  log "Feito isso, o Epoptes deverá funcionar normalmente.${RESET}"
}

pre_upgrade() {
	log "Iniciando upgrade"
}

post_upgrade() {
	log "Finalizando upgrade"
}
